### PR TITLE
fix nb4

### PR DESCRIPTION
**Pull request by juliettelavoie**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [ ] (If applicable) Tests have been added.
- [ ] This PR does not seem to break the templates.
- [ ] CHANGES.rst has been updated (with summary of main changes).
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

* for notebook 4 to not break randomly

### CODE REVIEW

**Comment by juliettelavoie** [comment]
ok, got it to work with a more simple example. Unsure, if the problem is actually fixed or I am just lucky this one time.

**Review by RondeauG — APPROVED** [review]
Faudra enlever la partie commentée, mais ça marche potentiellement ?

**Comment by juliettelavoie** [comment]
2/2 I think we are good!

**Comment by RondeauG** [comment]
Great!

**Pull request merged**
