### PR TITLE
[bot] Update GitHub Action Versions

### PR DESCRIPTION
**Pull request by Zeitsperre**
### GitHub Actions Version Updates
* **[actions/setup-python](https://github.com/actions/setup-python)** published a new release **[v5.0.0](https://github.com/actions/setup-python/releases/tag/v5.0.0)** on 2023-12-06T10:59:28Z
* **[mamba-org/setup-micromamba](https://github.com/mamba-org/setup-micromamba)** published a new release **[v1.7.3](https://github.com/mamba-org/setup-micromamba/releases/tag/v1.7.3)** on 2023-12-14T16:49:55Z
* **[actions/labeler](https://github.com/actions/labeler)** published a new release **[v5.0.0](https://github.com/actions/labeler/releases/tag/v5.0.0)** on 2023-12-04T14:14:37Z

### CODE REVIEW

**Comment by Zeitsperre** [comment]
FYI: since my workflow token is being used to generate the PR, I can't review it!

**Review by RondeauG — APPROVED** [review]

**Comment by Zeitsperre** [comment]
@RondeauG 

I imagine that the docs are failing due to changes to data ?

**Comment by RondeauG** [comment]
> @RondeauG
> 
> I imagine that the docs are failing due to changes to data ?

@juliettelavoie It seems to be your Partition PR that breaks. The `latest` docs build also appears to have failed to compile. Any idea why?

**Comment by juliettelavoie** [comment]
ah damn it! I don't why this happens, but sometimes the build failed. I clicked on rebuild and then it passed. I just clicked on rebuild. Let's see if it works.

**Comment by juliettelavoie** [comment]
rebuild worked

**Pull request merged**
