### PR TITLE
add security workflow and bumpversion actions

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] `pre-commit` hooks are installed/active in my local clone (`$ pre-commit install`)
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added
- [ ] `bumpversion patch` has been called on this branch

### What kind of change does this PR introduce?

* Adds a security analysis workflow and an automated bumpversion workflow

### Does this PR introduce a breaking change?

No.

### CODE REVIEW

**Review by juliettelavoie — APPROVED** [review]
La version dans setup.py est encore 0.1.0 ( mais on est au release 0.2.0). Je pense qu'il faudrait mettre ça à jour avant d'activer un bump version automatique.

**Comment by Zeitsperre** [comment]
@RondeauG

I noticed that you've been bumping the _minor_ version on each merged PR. Should I change the default auto bumpversion to be _minor_?

**Comment by RondeauG** [comment]
You can look at the conversation on Slack regarding this.
If we mimic `xclim`, we'd go from 0.2.0 --> 0.2.1 --> 0.2.3 --> etc. with each PR. Then at regular(ish) interval, we'd bump the _minor_ to 0.3.0, 0.4.0, etc.

The first release was 0.2.0 (bumping from our private 0.1.x). It is now 0.2.1, since I've pushed a PR. Yours would make it 0.2.2. Makes sense or not?

**Note:** After comparing our repo with `xclim` I did change HISTORY.rst to track the changes to our future 0.3.0, instead of having one entry per PR. I think that's how it should be done?

**Comment by RondeauG** [comment]
Feel free to tell me that I'm fully wrong or that I've messed up some files ;)

**Comment by Zeitsperre** [comment]
My mistake! No, everything looks good from my end. Sorry for the confusion.

**Pull request merged**
