### PR TITLE
Fix stack drop nans

### LINKED ISSUE #128: stack_drop_nans fails if intermediate directories don't exist
### Setup Information

- xscen version: 0.4.10b
- Python version: 3.9.10
- Operating System: Doris

### Description

line 135: should be changed to os.makedirs(..., exist_ok = True)

### Steps To Reproduce

_No response_

### Additional context

_No response_

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### PR DESCRIPTION
**Pull request by sg2475962**
### Pull Request Checklist:
- [x] `pre-commit` hooks are installed/active in my local clone (`$ pre-commit install`)
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [x] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [-] If a merge request has been made in parallel to this PR in xscen-notebooks, it is merged and the submodules have been updated.
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

- Fix #128 

### Does this PR introduce a breaking change?
- no

### CODE REVIEW

**Comment by aulemahal** [comment]
The test errors are not your fault, but rather an update of `pyESMF` that has changed how the package is imported...

**Comment by Zeitsperre** [comment]
@aulemahal Should we be pinning something somewhere?

**Comment by aulemahal** [comment]
Well, I guess yeah. `ESMpy < 8.4`

**Review by aulemahal — APPROVED** [review]
Looks good to me!

**Pull request merged**
