### PR TITLE
fix regrid for snakemake

### LINKED ISSUE #399: Add <= pin on xclim
### Addressing a Problem?

When xclim updates with breaking changes, this can sometimes break xscen (e.g. today, with xscen at 0.8.3 on conda-forge and xclim at 0.49.0). Since the packages are so tightly linked, it seems very likely that this will often occur.

### Potential Solution

Add xclim <= test-version (and potentially xclim >= functioning version) pins in environment.yml

### Additional context

Annoyingly my apps broke while this bug was occuring, but because the delay on this version release is around 3 hours, it's not worth fixing in my git repo.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### LINKED ISSUE #411: Regridding weights not properly reused
It seems like the regridding weights in regrid_dataset are not reused as expected from the weights_location keyword.

The kwargs set at
https://github.com/Ouranosinc/xscen/blob/99981803953c11d4317c576b7808403045606cca/src/xscen/regrid.py#L132

are not passed to xe.Regridder? They should be assigned to regridder_kwargs instead of kwargs

https://github.com/Ouranosinc/xscen/blob/99981803953c11d4317c576b7808403045606cca/src/xscen/regrid.py#L142

Some benchmarks with the original code:
Initial regrid dataset in fn test_xarray_regrid took  18.9291 seconds
Second regrid dataset in fn test_xarray_regrid took  13.4746 seconds

And by assigning 'weights' and 'reuse_weights' to regridder_kwargs
Initial regrid dataset in fn test_xarray_regrid took  16.8666 seconds
Second regrid dataset in fn test_xarray_regrid took  4.2991 seconds

Fixed in f12895a084d8d3521e8c721c7c2a37955fa59c07

### PR DESCRIPTION
**Pull request by juliettelavoie**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #399
    - This PR fixes #411
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [x] (If applicable) Tests have been added.
- [x] This PR does not seem to break the templates.
- [x] CHANGELOG.rst has been updated (with summary of main changes).
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

* write regrid weights in file with domain name

### Does this PR introduce a breaking change?
no

### Other information:
Previously, we would only do one regrid at the time. With snakemake, they can be done synchronously. This means we need the name of the domain in the name of the file, or different task try to write on the same file.

PVI: @oumoukal @aulemahal

### CODE REVIEW

**Comment by RondeauG** [comment]
Could you also include the fix to #411? The fix was given here: https://github.com/Ouranosinc/xscen/commit/f12895a084d8d3521e8c721c7c2a37955fa59c07

**Review by RondeauG — APPROVED** [review]
Good to go once `xclim v0.50` is available and fixes the tests.

**Comment by RondeauG** [comment]
Could you also add a `<0.51` to `xclim`, to help with #399 and future breaking changes?

**Comment by juliettelavoie** [comment]
I pinned xarray <2024.06.0. I think the failing tests in `adjust` were related to https://github.com/pydata/xarray/issues/9138.

**Comment by juliettelavoie** [comment]
@Zeitsperre do you have an idea what is the issue for py310-covervalls ?

**Pull request merged**
