### PR TITLE
Create template

### LINKED ISSUE #151: Add templates
### Addressing a Problem?

There should be a few generic templates to use as examples, in something like `xscen/templates`.

### Potential Solution

_No response_

### Additional context

_No response_

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

### PR DESCRIPTION
**Pull request by juliettelavoie**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #151
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* A template workflow

### Does this PR introduce a breaking change?
no

### Other information:

Let me know if you think there should be more or less steps and comments.

### CODE REVIEW

**Review by RondeauG — APPROVED** [review]
Looks very clean!

My only comment is that `template1` is not really descriptive and might be confusing once we have multiple templates. Maybe something like `full_workflow_with_config`?

**Comment by Zeitsperre** [comment]
@juliettelavoie @RondeauG

Do we want this in v0.5.0? It's not too late.

**Comment by RondeauG** [comment]
> @juliettelavoie @RondeauG
> 
> Do we want this in v0.5.0? It's not too late.

Sure, that could be pretty useful.

**Comment by juliettelavoie** [comment]
> Looks very clean!
> 
> My only comment is that `template1` is not really descriptive and might be confusing once we have multiple templates. Maybe something like `full_workflow_with_config`?


Pas trop sur de "full" parce que si on ajoute des choses plus tard, ça ne sera plus "full"!
`basic_workflow_with_config`?

**Comment by Zeitsperre** [comment]
Merge when ready!

**Pull request merged**
