### PR TITLE
Uniformize environments and update dependencies

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Reorder the `environment` files to fit what's in  `setup.py` (an alphabetical order)
* Remove fixes for esmpy 8.4, as xESMF 0.7 takes care of that (the pin is bumped).
* Add a (brand new!) fix for esmpy 8.4 to avoid installing packages with pip with running `pip install -e .`  on xscen
* Remove `numba` for the envs, it is not a direct dep and the bug related to version 0.55 is caduc with 0.56.
* Uniformize the two envs : h5netcdf, pyarrow, fsspec

### Does this PR introduce a breaking change?
No.

### Other information:
This still install `netCDF4` 1.6.2, I'm not sure if  this version has been fixed or not?

### CODE REVIEW

**Review by Zeitsperre — APPROVED** [review]

**Comment by aulemahal** [comment]
Well...
It works on my machine though...

**Comment by Zeitsperre** [comment]
Looks like an issue with ESMF?

**Comment by aulemahal** [comment]
Related RTD issue is : readthedocs/readthedocs.org#4067. We will need to patch this environment variable in the code, I'll push something.

**Comment by Zeitsperre** [comment]
I'm just curious, but is there any way for us to manually restart the environment using the `.readthedocs.yml`? I.e.:
```
build:
  jobs:
    pre-build:
      - conda deactivate
      - conda activate xscen-env
```

**Comment by aulemahal** [comment]
Well, I thought of that and decided not to do it for 2 reasons:
- I didn't want to interfere with RTD's machinery.
- Can you cal `conda activate` if you haven't called `conda init` ? Does RTD call the latter? I'm suspecting it doesn't and this is why the conventional activation mechanism isn't used.

**Comment by Zeitsperre** [comment]
That makes sense. Was just wondering. Your fix is clear enough for me. :+1:

**Pull request merged**
