### PR TITLE
Force notebooks to always be executed

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Forces notebooks to be executed.

### Does this PR introduce a breaking change?

No.

### Other information:

The previous method should have worked. There might be more going on here.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@RondeauG The cell that appears to be failing is one that calls an instance of `dask.ProgressBar`: 
image

I know that this is a major issue when running notebooks, as this asynchronous process does not necessarily block the execution of the next cell. Though the fact that this is failing within the cell tells me that it might simply be `dask` related. You might need to supply some kwargs to not use `dask`?

**Comment by RondeauG** [comment]
Ok, I'll look into it.

**Comment by Zeitsperre** [comment]
@RondeauG Well done! I think this is good to merge!

**Review by RondeauG — APPROVED** [review]
Alright, this seems to be working!

**Pull request merged**
